# Generated by Django 5.0.4 on 2024-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_siize_wallpaper_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='state',
            field=models.CharField(choices=[('0', '不可下载'), ('1', '可下载')], default='1', max_length=1, verbose_name='状态'),
        ),
    ]
